export const BOOT = {
  LOAD_SUCCESS: 'BOOT_LOAD_SUCCESS'
};

export const PEOPLE = {
  LOAD_SUCCESS: 'PEOPLE_LOAD_SUCCESS',
  UNLOAD_SUCCESS: 'PEOPLE_UNLOAD_SUCCESS'
};

export const PLANET = {
  LOAD_SUCCESS: 'PLANET_LOAD_SUCCESS',
  UNLOAD_SUCCESS: 'PLANET_UNLOAD_SUCCESS'
};

export const FILM = {
  LOAD_SUCCESS: 'FILM_LOAD_SUCCESS',
  UNLOAD_SUCCESS: 'FILM_UNLOAD_SUCCESS'
};

export const VEHICLE = {
  LOAD_SUCCESS: 'VEHICLE_LOAD_SUCCESS',
  UNLOAD_SUCCESS: 'VEHICLE_UNLOAD_SUCCESS'
};

export const SPECIES = {
  LOAD_SUCCESS: 'SPECIES_LOAD_SUCCESS',
  UNLOAD_SUCCESS: 'SPECIES_UNLOAD_SUCCESS'
};

export const STARSHIP = {
  LOAD_SUCCESS: 'STARSHIP_LOAD_SUCCESS',
  UNLOAD_SUCCESS: 'STARSHIP_UNLOAD_SUCCESS'
};
